FROM gradle:7.2.0-jdk11 AS build

WORKDIR /app/

COPY . .

RUN ./gradlew clean test build

FROM openjdk:11

COPY --from=build /app/build/libs/restaurant-0.0.1-SNAPSHOT.jar /app/libs/restaurant.jar

EXPOSE 8080

WORKDIR /app/libs/

CMD ["java", "-jar", "/app/libs/restaurant.jar"]
